development:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_dev
  pool: 2
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_test
  pool: 2
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_prod
  pool: 2
  username: root
  password: root