development:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_dev
  pool: 2
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_test
  pool: 2
  username: root
  password: root

cucumber:
  adapter: postgresql
  encoding: unicode
  database: nbforms_app_test
  pool: 2
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>